---
title: "Research Log 10/28"
author: "Emerson Webb"
date: "10/28/2017"
output: html_document
---

###Research Log

This week I read Hemant Ishwaran's "Variable Importance for Binary Regression Trees and Forests" which was an interesting and likely useful paper.  Ishwaran's paper is primarily concerned with theoretically characterizing Variable Importance from the perspective of Mean Decrease in Accuracy (MDA).  Noting Strobl et al.'s work in 2007 regarding bias in random forest variable importance measures, Ishwaran focuses on the regression setting.  With regression trees and forests, one measure of variable importance is the permutation variable importance originally suggested by Breiman in 1999/2001 (I'm not sure on the date on Permutation VI).  Strobl's later work defines and ran simulations on Conditional Permuted Variable Importance, and this past year Owen's developed the Infforest Variable Importance.  It's important to note that Ishwaran's work here is prior to Strobl's Conditional VI.  Rather than trying to characterize the theory of Permuted VI, Ishwaran develops a framework in which to determine the importance of predictor $X_v$ out of predictors $x_1,\ldots,x_d$ used to build a tree, one sends a test point $\textbf{x}$ down the tree until a split relying on $x_v$ is reached.  From that split onwards, random left-right path is followed down through the tree until a random terminal node is reached.  The test point $\mathbf{x}$ is then assigned the terminal value of that random terminal node as it's prediction. It turns out this scheme is useful in characterizing some of the behavior seen empirically in permuted VI.  In addition, Ishwaran is able to extend his theory to analyze paired association values which can capture joint/interaction effects in the data in the limiting case.  It would be interesting to implement this scheme in a regression tree/forest to see how it performs.  Some thoughts I have after reading Ishwaran's paper is how might the distribution of random terminal node values obtained from the noising up can be characterized in the finite sample case.  Furthermore, I would be interested in seeing if this framework can be extended to analyze Permuted VI, Conditionl Permuted VI, or Infforest VI in a manner that captures the theoretical properties of these respectiv variable importance measures.  

In addition, I read Aurora's thesis, specifically about Infforest VI and I am still trying to understand the different components that go into that measure of variable importance.  It is quite complicated, with many different parts, but is certainly an interesting measure of variable importance.  

For the following week, I'll be continuing work on implementing the Random Forest Algorithm in R from scratch.  The big focus is to write the tree-building method and predict method so that any test data points can be sent down the tree and also to compute OOB estimate of MSE. Another aspect that I need to figure out is how to keep track of how the data is being partitioned in order to compute RSS or whatever metric being used to build the CART trees.  

For reading, I will be reading the two chapters of Gilles Louppe's PhD thesis on understanding MDI (Mean Decrease in Impurity) variable importance measures in forest ensembles. I will also begin to read Mark van der Laan's "Statistical Infernce for Variable Importance".
